export const environments = {
  baseUrl :  "https://catalogo.consultaema.mx:3000",
  Token: "ad922eb32d4779baf37a645d0c62809435464bf1",
  URLs:[
    {
      path:"search",
      parameters:[
        {path:"acreditacion__id__icontains:"},
        {path:"acreditacion__cliente__nombre__icontains:"}
      ]
    },
    {
      path:"search-calibracion",
      parameters:[
        {path:"acreditacion__icontains:"},
        {path:"razonSocial__icontains:"}
      ]
    },
    {
      path:"search-ensayos",
      parameters:[
        {path:"acreditacion__icontains:"},
        {path:"razonSocial__icontains:"}
      ]
    },
    {
      path:"search-unidades-inspeccion",
      parameters:[
        {path:"acreditacion__icontains:"},
        {path:"razonSocial__icontains:"}
      ]
    },
    {
      path:"search-analisis-clinicos",
      parameters:[
        {path:"acreditacion__icontains:"},
        {path:"razonSocial__icontains:"}
      ]
    },
    {
      path:"search-pea",
      parameters:[
        {path:"acreditacion__icontains:"},
        {path:"razonSocial__icontains:"}
      ]
    },
    {
      path:"search-pmr",
      parameters:[
        {path:"acreditacion__icontains:"},
        {path:"razonSocial__icontains:"}
      ]
    },
    {
      path:"search-bancos-sangre",
      parameters:[
        {path:"acreditacion__icontains:"},
        {path:"razonSocial__icontains:"}
      ]
    },
    {
      path:"search-radiologia",
      parameters:[
        {path:"acreditacion__icontains:"},
        {path:"razonSocial__icontains:"}
      ]
    }
  ]
}
