// Generated by https://quicktype.io

export interface Ema<T> {
  count:    number;
  next:     string;
  previous: null;
  results:  T[] ;
  url?:string
}

export type Catalogo =  LaboratorioCalibracion| LaboratorioEnsayo | OrganismoCertificacion
| UnidadInspeccion | LabAnalisisClinicos | ProvEnsayosApitud | ProductosMRC | BancoSangre | GRadiologiaImagen


export interface OrganismoCertificacion {
  TYPE: "OC"
  id:                                       string;
  acreditacion__id:                         string;
  acreditacion__status__nombre:             string;
  alcance__id:                              string;
  alcance__nombre:                          string;
  acreditacion__cliente__nombre:            string;
  mixto:                                    string;
  mixAcredAlcance:                          string;
  alcance__area__id:                        string;
  alcance__area__nombre:                    string;
  domicilio__cp__municipio__estado__nombre: string;
  noAcredREA:                               string;
  fechaInicio:                              Date;
  fechaUltimaRev:                           null;
  normaAplicable:                           string;
  created_at:                               Date;
  updated_at:                               Date;
  acreditacion:                             string;
  normaAcreditacion:                        string;
  alcance:                                  string;
}

export interface UnidadInspeccion {
  TYPE:"UI"
  id:                number;
  id__mix:           string;
  normaAcred:        string;
  rama:              string;
  area:              string;
  razonSocial:       string;
  nombreLaboratorio: string;
  domicilio:         string;
  telefono:          string;
  email:             string;
  email2:            string;
  acreditacion:      string;
  referencia:        string;
  responsable:       string;
  fechaInicio:       Date;
  fechaFinal:        string;
  norma:             string;
  gerenteTecnico:    string;
  gerenteSustituto:  string;
  estado:            string;
  nomArchivo:        string;
  observacion:       string;
  normax:            string;
  status:            string;
  fechaSuspCanc:     string;
  motivoSuspCanc:    string;
  tipo:              string;
  dependencia:       string;
  persona:           string;
  sitio:             string;
  testificado:       string;
  region:            string;
  created_at:        Date;
  updated_at:        Date;
}

//
export interface LaboratorioCalibracion {
  TYPE: 'LC'
  id:                number;
  id__mix:           string;
  acreditacion:      string;
  rama:              string;
  area:              string;
  razonSocial:       string;
  nombreLaboratorio: string;
  domicilio:         string;
  telefono:          string;
  email:             string;
  referencia:        string;
  repAutorizado:     string;
  fechaInicio:       Date;
  fechaFinal:        string;
  norma:             string;
  metodoPrueba:      string;
  signatario:        string;
  estado:            string;
  nomArchivo:        string;
  subrama:           string;
  sector:            string;
  status:            string;
  nomArchivoSusp:    string;
  fechaSuspension:   string;
  motivoSuspension:  string;
  nomArchivoCanc:    string;
  fechaCancelacion:  string;
  motivoCancelacion: string;
  dependencia:       string;
  tipoLaboratorio:   string;
  region:            string;
  gnlpaa:            string;
  web:               string;
  fechaComite:       Date;
  created_at:        Date;
  updated_at:        Date;
}


export interface LaboratorioEnsayo {
  TYPE:'LP'
  id:                number;
  id__mix:           string;
  acreditacion:      string;
  rama:              string;
  area:              string;
  razonSocial:       string;
  nombreLaboratorio: string;
  domicilio:         string;
  telefono:          string;
  email:             string;
  referencia:        string;
  repAutorizado:     string;
  fechaInicio:       Date;
  fechaFinal:        string;
  norma:             string;
  metodoPrueba:      string;
  signatario:        string;
  estado:            string;
  nomArchivo:        string;
  subrama:           string;
  sector:            string;
  status:            string;
  nomArchivoSusp:    string;
  fechaSuspension:   string;
  motivoSuspension:  string;
  nomArchivoCanc:    string;
  fechaCancelacion:  string;
  motivoCancelacion: string;
  dependencia:       string;
  tipoLaboratorio:   string;
  region:            string;
  gnlpaa:            string;
  web:               string;
  fechaComite:       string;
  created_at:        Date;
  updated_at:        Date;

}

export interface LabAnalisisClinicos {
  TYPE: "CL"
  id:                number;
  id__mix:           string;
  acreditacion:      string;
  rama:              string;
  area:              string;
  razonSocial:       string;
  nombreLaboratorio: string;
  domicilio:         string;
  telefono:          string;
  email:             string;
  referencia:        string;
  repAutorizado:     string;
  fechaInicio:       Date;
  fechaFinal:        string;
  norma:             string;
  metodoPrueba:      string;
  signatario:        string;
  estado:            string;
  nomArchivo:        string;
  subrama:           string;
  sector:            string;
  status:            string;
  nomArchivoSusp:    string;
  fechaSuspension:   string;
  motivoSuspension:  string;
  nomArchivoCanc:    string;
  fechaCancelacion:  string;
  motivoCancelacion: string;
  dependencia:       string;
  region:            string;
  fechaComite:       Date;
  created_at:        Date;
  updated_at:        Date;
}


export interface ProvEnsayosApitud {
  TYPE:"PEA"
  id:                number;
  id__mix:           string;
  acreditacion:      string;
  rama:              string;
  area:              string;
  razonSocial:       string;
  nombreLaboratorio: string;
  domicilio:         string;
  telefono:          string;
  email:             string;
  referencia:        string;
  repAutorizado:     string;
  fechaInicio:       Date;
  fechaFinal:        string;
  norma:             string;
  metodoPrueba:      string;
  signatario:        string;
  estado:            string;
  nomArchivo:        string;
  subrama:           string;
  sector:            string;
  status:            string;
  nomArchivoSusp:    string;
  fechaSuspension:   string;
  motivoSuspension:  string;
  nomArchivoCanc:    string;
  fechaCancelacion:  string;
  motivoCancelacion: string;
  dependencia:       string;
  tipoLaboratorio:   string;
  region:            string;
  gnlpaa:            string;
  web:               string;
  fechaComite:       Date;
  created_at:        Date;
  updated_at:        Date;
}


export interface ProductosMRC {
  TYPE:"PMR"
  id:                number;
  id__mix:           string;
  rama:              string;
  area:              string;
  razonSocial:       string;
  nombreProductor:   string;
  domicilio:         string;
  telefono:          string;
  email:             string;
  acreditacion:      string;
  referencia:        string;
  repAutorizado:     string;
  fechaInicio:       Date;
  fechaFinal:        string;
  norma:             string;
  estado:            string;
  nomArchivo:        string;
  subcategoria:      string;
  sector:            string;
  status:            string;
  nomArchivoSusp:    string;
  fechaSuspension:   Date;
  motivoSuspension:  string;
  nomArchivoCanc:    string;
  fechaCancelacion:  string;
  motivoCancelacion: string;
  dependencia:       string;
  tipoPMR:           string;
  region:            string;
  fechaComite:       Date;
  created_at:        Date;
  updated_at:        Date;
}

export interface BancoSangre {
  TYPE:"BS"
  id:                number;
  id__mix:           string;
  acreditacion:      string;
  rama:              string;
  area:              string;
  razonSocial:       string;
  nombreLaboratorio: string;
  domicilio:         string;
  telefono:          string;
  email:             string;
  referencia:        string;
  repAutorizado:     string;
  fechaInicio:       Date;
  fechaFinal:        string;
  norma:             string;
  metodoPrueba:      string;
  signatario:        string;
  estado:            string;
  nomArchivo:        string;
  subrama:           string;
  sector:            string;
  status:            string;
  nomArchivoSusp:    string;
  fechaSuspension:   string;
  motivoSuspension:  string;
  nomArchivoCanc:    string;
  fechaCancelacion:  string;
  motivoCancelacion: string;
  dependencia:       string;
  region:            string;
  fechaComite:       Date;
  created_at:        Date;
  updated_at:        Date;
}

export interface GRadiologiaImagen {
  TYPE:"RI"
  id:                number;
  id__mix:           string;
  acreditacion:      string;
  rama:              string;
  area:              string;
  razonSocial:       string;
  nombreLaboratorio: string;
  domicilio:         string;
  telefono:          string;
  email:             string;
  referencia:        string;
  repAutorizado:     string;
  fechaInicio:       Date;
  fechaFinal:        string;
  norma:             string;
  metodoPrueba:      string;
  signatario:        string;
  estado:            string;
  nomArchivo:        string;
  subrama:           string;
  sector:            string;
  status:            string;
  nomArchivoSusp:    string;
  fechaSuspension:   string;
  motivoSuspension:  string;
  nomArchivoCanc:    string;
  fechaCancelacion:  string;
  motivoCancelacion: string;
  dependencia:       string;
  region:            string;
  fechaComite:       string;
  created_at:        Date;
  updated_at:        Date;
}

export interface Filtro{
  nombre: string
  filtro:string
}



export interface Busqueda<T>{
  tipo:T
  content:any[]
}



